// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package teststyledtext.proxies;

public class TestContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestStyledText.TestContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text1("Text1"),
		Text2("Text2"),
		Text3("Text3"),
		Text4("Text4");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testContextMendixObject)
	{
		if (testContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testContextMendixObject = testContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static teststyledtext.proxies.TestContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new teststyledtext.proxies.TestContext(context, mendixObject);
	}

	public static teststyledtext.proxies.TestContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return teststyledtext.proxies.TestContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of Text1
	 */
	public final java.lang.String getText1()
	{
		return getText1(getContext());
	}

	/**
	 * @param context
	 * @return value of Text1
	 */
	public final java.lang.String getText1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text1.toString());
	}

	/**
	 * Set value of Text1
	 * @param text1
	 */
	public final void setText1(java.lang.String text1)
	{
		setText1(getContext(), text1);
	}

	/**
	 * Set value of Text1
	 * @param context
	 * @param text1
	 */
	public final void setText1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text1)
	{
		getMendixObject().setValue(context, MemberNames.Text1.toString(), text1);
	}

	/**
	 * @return value of Text2
	 */
	public final java.lang.String getText2()
	{
		return getText2(getContext());
	}

	/**
	 * @param context
	 * @return value of Text2
	 */
	public final java.lang.String getText2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text2.toString());
	}

	/**
	 * Set value of Text2
	 * @param text2
	 */
	public final void setText2(java.lang.String text2)
	{
		setText2(getContext(), text2);
	}

	/**
	 * Set value of Text2
	 * @param context
	 * @param text2
	 */
	public final void setText2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text2)
	{
		getMendixObject().setValue(context, MemberNames.Text2.toString(), text2);
	}

	/**
	 * @return value of Text3
	 */
	public final java.lang.String getText3()
	{
		return getText3(getContext());
	}

	/**
	 * @param context
	 * @return value of Text3
	 */
	public final java.lang.String getText3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text3.toString());
	}

	/**
	 * Set value of Text3
	 * @param text3
	 */
	public final void setText3(java.lang.String text3)
	{
		setText3(getContext(), text3);
	}

	/**
	 * Set value of Text3
	 * @param context
	 * @param text3
	 */
	public final void setText3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text3)
	{
		getMendixObject().setValue(context, MemberNames.Text3.toString(), text3);
	}

	/**
	 * @return value of Text4
	 */
	public final java.lang.String getText4()
	{
		return getText4(getContext());
	}

	/**
	 * @param context
	 * @return value of Text4
	 */
	public final java.lang.String getText4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text4.toString());
	}

	/**
	 * Set value of Text4
	 * @param text4
	 */
	public final void setText4(java.lang.String text4)
	{
		setText4(getContext(), text4);
	}

	/**
	 * Set value of Text4
	 * @param context
	 * @param text4
	 */
	public final void setText4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text4)
	{
		getMendixObject().setValue(context, MemberNames.Text4.toString(), text4);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testContextMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final teststyledtext.proxies.TestContext that = (teststyledtext.proxies.TestContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
