// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("8fbb1aa1-d2fa-4951-bfe0-61558aca785e"),
	Geocodio("123d59a3-689a-4f89-adf5-4024bc19c529"),
	LocationIQ("dcc0f247-5217-4f5e-8cde-6a8c923727d4"),
	MapQuest("e95ff7d2-c18a-4ef6-81a3-aa18c554ef83");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
