// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Platform
{
	Web("e318958f-e56c-4d9f-8b62-8780c9142619"),
	Native_mobile("1b2ba111-92c9-48d8-96af-56505b7eb476"),
	Hybrid_mobile("61416a0e-7061-439f-bff7-4d77b8dce2ee");

	private final java.lang.String i18nCaptionKey;
	
	private Platform(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
