// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public class TestContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestModule.TestContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text1("Text1"),
		Text2("Text2"),
		Text3("Text3"),
		Text4("Text4");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestModule.TestContext"));
	}

	protected TestContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testContextMendixObject)
	{
		if (testContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestModule.TestContext", testContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestModule.TestContext");

		this.testContextMendixObject = testContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testmodule.proxies.TestContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testmodule.proxies.TestContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testmodule.proxies.TestContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmodule.proxies.TestContext(context, mendixObject);
	}

	public static testmodule.proxies.TestContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmodule.proxies.TestContext.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Text1
	 */
	public final java.lang.String getText1()
	{
		return getText1(getContext());
	}

	/**
	 * @param context
	 * @return value of Text1
	 */
	public final java.lang.String getText1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text1.toString());
	}

	/**
	 * Set value of Text1
	 * @param text1
	 */
	public final void setText1(java.lang.String text1)
	{
		setText1(getContext(), text1);
	}

	/**
	 * Set value of Text1
	 * @param context
	 * @param text1
	 */
	public final void setText1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text1)
	{
		getMendixObject().setValue(context, MemberNames.Text1.toString(), text1);
	}

	/**
	 * @return value of Text2
	 */
	public final java.lang.String getText2()
	{
		return getText2(getContext());
	}

	/**
	 * @param context
	 * @return value of Text2
	 */
	public final java.lang.String getText2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text2.toString());
	}

	/**
	 * Set value of Text2
	 * @param text2
	 */
	public final void setText2(java.lang.String text2)
	{
		setText2(getContext(), text2);
	}

	/**
	 * Set value of Text2
	 * @param context
	 * @param text2
	 */
	public final void setText2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text2)
	{
		getMendixObject().setValue(context, MemberNames.Text2.toString(), text2);
	}

	/**
	 * @return value of Text3
	 */
	public final java.lang.String getText3()
	{
		return getText3(getContext());
	}

	/**
	 * @param context
	 * @return value of Text3
	 */
	public final java.lang.String getText3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text3.toString());
	}

	/**
	 * Set value of Text3
	 * @param text3
	 */
	public final void setText3(java.lang.String text3)
	{
		setText3(getContext(), text3);
	}

	/**
	 * Set value of Text3
	 * @param context
	 * @param text3
	 */
	public final void setText3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text3)
	{
		getMendixObject().setValue(context, MemberNames.Text3.toString(), text3);
	}

	/**
	 * @return value of Text4
	 */
	public final java.lang.String getText4()
	{
		return getText4(getContext());
	}

	/**
	 * @param context
	 * @return value of Text4
	 */
	public final java.lang.String getText4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text4.toString());
	}

	/**
	 * Set value of Text4
	 * @param text4
	 */
	public final void setText4(java.lang.String text4)
	{
		setText4(getContext(), text4);
	}

	/**
	 * Set value of Text4
	 * @param context
	 * @param text4
	 */
	public final void setText4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text4)
	{
		getMendixObject().setValue(context, MemberNames.Text4.toString(), text4);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmodule.proxies.TestContext that = (testmodule.proxies.TestContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestModule.TestContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
