// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("e89d59c4-a02a-495e-a48e-0b9696fd8e23"),
	startsWith("962d5a82-d1d4-4034-affb-f88be9c9b008"),
	endsWith("122ef237-d2b6-4ed7-b62c-0f1f6d9fc749"),
	between("dc8b66f7-7078-47d8-bb32-0d0d1c3210ba"),
	greater("46ae8add-3be1-4eae-8863-0522ec250338"),
	greaterEqual("60eb0bdc-d80c-4f7d-ac17-b2c4868e0da0"),
	equal("49868666-fd0b-42b7-934e-1765bd3a6ef6"),
	notEqual("0a75823d-34d5-4d68-9eb9-d6eedde37267"),
	smaller("e67ea649-4829-4fa8-ab3c-e9b038d1d985"),
	smallerEqual("fb52d732-a848-481d-b641-b67ac77d3787"),
	empty("a7c72074-9f2e-4449-8c49-d6bd89260f98"),
	notEmpty("93ed838e-cfbb-4682-9211-bbaa6092b7a0");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
