// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("fd62744e-cca0-4e3f-b4b8-37699df9016e"),
	startsWith("bd2937da-dea9-421d-80f6-1744e8640923"),
	endsWith("070637cf-e4e1-4d30-a7cc-912f1ad89688"),
	between("91bbc8f8-4265-43dd-ac82-43c920c1753c"),
	greater("119e2fcb-d4f7-42bb-a2dc-f3a964846a0c"),
	greaterEqual("8e0bb00c-8780-4cc7-816a-a7e6c3cd6488"),
	equal("dcb76260-4bbd-4838-b852-7ce347bbac3a"),
	notEqual("419a4a31-b92d-4faf-bc0c-3b53983f0e20"),
	smaller("2a79f2d2-60c3-44c8-b799-1c69ed282508"),
	smallerEqual("076659a0-4616-4df2-b5a1-30e4bef45f8a"),
	empty("81a3dfdd-acef-445c-b06d-6110e68debb6"),
	notEmpty("1ad5c986-6812-4ef9-8831-26851e9c80ae");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
