// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("b725d791-525f-45d6-92fe-908fc48493ea"),
	denied("0dc1b004-8c20-4992-8e62-30856a0ac767"),
	limited("8fb1f75d-a021-44ff-a798-9e8368c7d2f5"),
	granted("9ce8b532-e2a0-4c58-bbff-97a1c2fade4f"),
	blocked("66a1fed5-56e7-44eb-96eb-9bb46e9b2600");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
