// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("3680a9a7-cb8b-4035-8c68-66faab83e011"),
	denied("f283f326-302e-45dc-9991-77be97a46bde"),
	limited("3e4eb1ae-0431-40a5-8d81-cdd8e6e115a4"),
	granted("c11a25e4-c9a6-4871-a972-b75a26b62737"),
	blocked("81b73bc4-3736-4f03-8df1-6beabdfbc7c5");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
