// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("18c6aebb-a66e-4344-9ecd-44ef4a4b71fb"),
	low("dbee554e-0b7e-42ba-a171-d54ae7e6fd81"),
	medium("acb4827b-ae7a-473a-911e-6979840fc443"),
	high("702eef89-d7e0-4f29-a091-1e059b4407d7"),
	custom("3755eb44-18c5-4971-a04d-0c62799912f2");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
