// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("d5431e08-e81f-4f06-b87a-660e2b12593b"),
	low("21b8f5b1-5d58-4d91-9030-37e652fc8ef9"),
	medium("3fb8fcbb-6e1b-420b-abd5-f99503f8f63a"),
	high("82d14938-c496-4102-98c1-6f46ba250599"),
	custom("b45533e4-19a6-4011-a308-523901c8f4ce");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
