// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarStyle
{
	DefaultStyle("00d8013c-6d77-4236-a2ed-43c4b6838660"),
	LightContentStyle("9ff13ba0-e5fd-464a-98f1-fb48a20c418c"),
	DarkContentStyle("91bc4300-03eb-4ed0-bf86-0d9851443831");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
